function [expConfig,csiMatrix] = readDatFile(filename)
%% Filename parsing
%   - Only considering the raw ".dat" file
filename = split(filename,".");

%   Input checking
assert( ...
    length(filename) == 1 || (length(filename) == 2 && contains(filename(2),'dat')), ...
    'Wrong input format of Read_File(filename)');

filename = filename(1);

%% Analysis the File Name
[ ...
    expConfig.user, ...
    expConfig.gesture, ...
    expConfig.number, ...
    expConfig.intensity, ...
    expConfig.loc, ...
    expConfig.dir, ...
    expConfig.date ...
] = getExpConfigFromFileName(filename);

%% Read the data of .DAT file
csiMatrix = getReadingFromDatFile(filename+".dat");
end