function [expConfig,csiMatrix,csiMatrixInfo] = readDatFile(filepath)
%% Filename parsing
%   - Only considering the raw ".dat" file
%   Input checking
filename = split(filepath,"/");
filename = filename(end);
assert(contains(filename,'.dat'), 'File path needs complete extension name <file.dat>');

%% Analysis the File Name
[ ...
    expConfig.user, ...
    expConfig.gesture, ...
    expConfig.number, ...
    expConfig.intensity, ...
    expConfig.loc, ...
    expConfig.dir, ...
    expConfig.date ...
] = getExpConfigFromFileName(filename);

%% Read the data of .DAT file
csiMatrix = getReadingFromDatFile(filepath);

%% Statistic the information of csiMatrix
csiMatrixInfo = getCsiMatrixInfo(csiMatrix);
end